export { default as HeroSection } from './hero-section'
export { default as ServiceOverview } from './service-overview'
export { default as Locations } from './locations'
export { default as RentalCategories } from './rental-categories'
export { default as Featured } from './featured'
